# Generated by Django 5.0.2 on 2025-10-13 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manual', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comando',
            name='comando',
            field=models.TextField(max_length=300),
        ),
    ]
