# Generated by Django 5.0.2 on 2025-10-17 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manual', '0004_artigo_autor_categoria_autor_categoria_criado_em_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comando',
            options={'ordering': ['ordem', '-criado_em']},
        ),
        migrations.AddField(
            model_name='comando',
            name='ordem',
            field=models.IntegerField(default=0),
        ),
    ]
